const productlist = [
  {
    id: 1,
    name: "Classic Logo T-Shirt",
    description: "Comfortable cotton t-shirt with embroidered company logo",
    category: "Apparel",
    brand: "Next Level",
    price: 24.99,
    rating: 4.5,
    image:
      "https://plus.unsplash.com/premium_photo-1718913936342-eaafff98834b?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 2,
    name: "Tech Backpack",
    description: "Water-resistant laptop backpack with multiple compartments",
    category: "Accessories",
    brand: "SwiftGear",
    price: 59.99,
    rating: 4.8,
    image: "https://media.istockphoto.com/id/1508207282/photo/travel-backpack.jpg?s=2048x2048&w=is&k=20&c=lklAP7NNPQTqjJ8mq1zzwXQbaAasZH4nx091C641HbY=",
  },
  {
    id: 3,
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with company branding and USB receiver",
    category: "Electronics",
    brand: "LogiTech",
    price: 34.99,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1707592691247-5c3a1c7ba0e3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 4,
    name: "Coffee Tumbler",
    description: "Stainless steel vacuum-insulated tumbler",
    category: "Drinkware",
    brand: "Yeti",
    price: 29.99,
    rating: 4.7,
    image: "https://media.istockphoto.com/id/1192614237/photo/blank-stainless-steel-tumbler-with-lid-for-branding-mock-up-3d-render-illustration.jpg?s=2048x2048&w=is&k=20&c=6KcJCN66TkdRL4ackUkbnDZDDGZLTYUXsDSGPZLmS8A=",
  },
  {
    id: 5,
    name: "Hoodie Sweatshirt",
    description: "Warm zip-up hoodie with embroidered logo",
    category: "Apparel",
    brand: "Champion",
    price: 49.99,
    rating: 4.6,
    image: "https://media.istockphoto.com/id/1142212979/photo/back-of-sweatshirt-with-hood-isolated-on-white-background.jpg?s=2048x2048&w=is&k=20&c=lfl2SD2WS4XfP8pdY4kc4RghCaETFqkKJLMzO_uMHmY=",
  },
  {
    id: 6,
    name: "Baseball Cap",
    description: "Adjustable cotton cap with embroidered logo",
    category: "Accessories",
    brand: "New Era",
    price: 19.99,
    rating: 4.4,
    image: "https://plus.unsplash.com/premium_photo-1678577239514-161fa41e8a4d?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 7,
    name: "Power Bank",
    description: "10000mAh portable charger with dual USB ports",
    category: "Electronics",
    brand: "Anker",
    price: 39.99,
    rating: 4.5,
    image: "https://media.istockphoto.com/id/1409737619/photo/a-mobile-phone-being-charged-using-a-power-bank-is-on-the-table.jpg?s=2048x2048&w=is&k=20&c=x91EgiVg28XvqQ-I3RPGNlh3BwSldxzdYF_ziEq4jFs=",
  },
  {
    id: 8,
    name: "Notebook Set",
    description: "Premium hardcover notebook with pen",
    category: "Stationery",
    brand: "Moleskine",
    price: 24.99,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1625533617580-3977f2651fc0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 9,
    name: "Desk Plant",
    description: "Mini succulent in branded ceramic pot",
    category: "Office Decor",
    brand: "GreenSpace",
    price: 15.99,
    rating: 4.0,
    image: "https://images.unsplash.com/photo-1512428813834-c702c7702b78?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 10,
    name: "Water Bottle",
    description: "BPA-free water bottle with measurements",
    category: "Drinkware",
    brand: "Nalgene",
    price: 14.99,
    rating: 4.6,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 11,
    name: "Laptop Sleeve",
    description: "Padded laptop sleeve with zipper closure",
    category: "Accessories",
    brand: "Case Logic",
    price: 29.99,
    rating: 4.4,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 12,
    name: "Wireless Earbuds",
    description: "Bluetooth earbuds with charging case",
    category: "Electronics",
    brand: "JBL",
    price: 79.99,
    rating: 4.3,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 13,
    name: "Desk Calendar",
    description: "Monthly desk calendar with company branding",
    category: "Office Supplies",
    brand: "AT-A-GLANCE",
    price: 12.99,
    rating: 4.1,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 14,
    name: "Phone Stand",
    description: "Adjustable aluminum phone stand",
    category: "Accessories",
    brand: "TechStand",
    price: 19.99,
    rating: 4.5,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 15,
    name: "Polo Shirt",
    description: "Classic fit polo with embroidered logo",
    category: "Apparel",
    brand: "Nike",
    price: 39.99,
    rating: 4.7,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 16,
    name: "Mouse Pad",
    description: "Premium cloth mouse pad with stitched edges",
    category: "Office Supplies",
    brand: "Corsair",
    price: 14.99,
    rating: 4.2,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 17,
    name: "Wireless Keyboard",
    description: "Slim wireless keyboard with numeric pad",
    category: "Electronics",
    brand: "Logitech",
    price: 49.99,
    rating: 4.6,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 18,
    name: "Drawstring Bag",
    description: "Lightweight drawstring bag with printed logo",
    category: "Accessories",
    brand: "Port & Company",
    price: 9.99,
    rating: 4.0,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 19,
    name: "Gift Card",
    description: "Digital gift card with custom denomination",
    category: "Gift Items",
    brand: "Store Brand",
    price: 50.0,
    rating: 4.9,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
  {
    id: 20,
    name: "Sticker Pack",
    description: "Assorted company logo stickers",
    category: "Accessories",
    brand: "Store Brand",
    price: 4.99,
    rating: 4.4,
    image: "https://media.istockphoto.com/id/1450349466/photo/man-wearing-green-t-shirt-with-universal-recycling-symbol-printed-on-chest.jpg?s=2048x2048&w=is&k=20&c=lhRlOJGseVE_ywbUDn4e2QdxGYOPYlVdBEEwTYpkacQ=",
  },
];

export default productlist;
